[package]
name = "api"
publish = false
version = "2.0.0-beta.6"
description = "An example Tauri Application showcasing the api"
edition = "2021"
rust-version = { workspace = true }
license = "Apache-2.0 OR MIT"

[lib]
name = "api_lib"
crate-type = [ "staticlib", "cdylib", "rlib" ]

[build-dependencies]
tauri-build = { workspace = true, features = [ "codegen", "isolation" ] }

[dependencies]
serde_json = { workspace = true }
serde = { workspace = true }
tiny_http = "0.12"
log = { workspace = true }
tauri-plugin-log = { path = "../../../plugins/log", version = "2.0.0-beta.3" }
tauri-plugin-fs = { path = "../../../plugins/fs", version = "2.0.0-beta.6", features = [ "watch" ] }
tauri-plugin-clipboard-manager = { path = "../../../plugins/clipboard-manager", version = "2.1.0-beta.1" }
tauri-plugin-dialog = { path = "../../../plugins/dialog", version = "2.0.0-beta.6" }
tauri-plugin-http = { path = "../../../plugins/http", features = [ "multipart" ], version = "2.0.0-beta.6" }
tauri-plugin-notification = { path = "../../../plugins/notification", version = "2.0.0-beta.4", features = [ "windows7-compat" ] }
tauri-plugin-os = { path = "../../../plugins/os", version = "2.0.0-beta.3" }
tauri-plugin-process = { path = "../../../plugins/process", version = "2.0.0-beta.3" }
tauri-plugin-shell = { path = "../../../plugins/shell", version = "2.0.0-beta.3" }

  [dependencies.tauri]
  workspace = true
  features = [
  "image-ico",
  "image-png",
  "isolation",
  "macos-private-api",
  "tray-icon",
  "protocol-asset"
]

[target."cfg(any(target_os = \"macos\", windows, target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
tauri-plugin-cli = { path = "../../../plugins/cli", version = "2.0.0-beta.3" }
tauri-plugin-global-shortcut = { path = "../../../plugins/global-shortcut", version = "2.0.0-beta.3" }
tauri-plugin-updater = { path = "../../../plugins/updater", version = "2.0.0-beta.4" }

[target."cfg(any(target_os = \"android\", target_os = \"ios\"))".dependencies]
tauri-plugin-barcode-scanner = { path = "../../../plugins/barcode-scanner/", version = "2.0.0-beta.4" }
tauri-plugin-nfc = { path = "../../../plugins/nfc", version = "2.0.0-beta.3" }
tauri-plugin-biometric = { path = "../../../plugins/biometric/", version = "2.0.0-beta.3" }

[target."cfg(target_os = \"windows\")".dependencies]
window-shadows = "0.2"

[features]
prod = [ "tauri/custom-protocol" ]
