# Copyright 2019-2023 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: Lint JavaScript

on:
  push:
    branches:
      - v1
      - v2
    paths:
      - ".github/workflows/lint-javascript.yml"
      - "plugins/*/guest-js/**"
      - ".eslintignore"
      - ".eslintrc.json"
      - ".prettierignore"
      - "**/package.json"
  pull_request:
    branches:
      - v1
      - v2
    paths:
      - ".github/workflows/lint-javascript.yml"
      - "plugins/*/guest-js/**"
      - ".eslintignore"
      - ".eslintrc.json"
      - ".prettierignore"
      - "**/package.json"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - uses: pnpm/action-setup@v2
        with:
          version: 8.x.x
          run_install: true
      - name: eslint
        run: pnpm lint
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - uses: pnpm/action-setup@v2
        with:
          version: 8.x.x
          run_install: true
      - name: prettier check
        run: pnpm format-check
